# name: Pull new tweets
# on:
#   schedule:
#     - cron: "*/60 * * * *"
# jobs:
#   pull-tweet:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#       - name: Build Actions
#         run: |
#           npm ci
#           npm run-script build

#       - name: Collect and Update
#         uses: ./.github/actions/PullTweetAction
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           twi-cons-key: ${{ secrets.TWITTERCONSUMERKEY }}
#           twi-cons-secret: ${{ secrets.TWITTERCONSUMERSECRET }}
#           twi-token-key: ${{ secrets.TWITTERTOKENKEY }}
#           twi-token-secret: ${{ secrets.TWITTERTOKENSECRET }}
