name: Pull new tweets
on:
  schedule:
    # UTC
    - cron: "24 2,10 * * *"
jobs:
  re-retweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Actions
        run: |
          npm ci
          npm run-script build

      - name: ReRetweet
        uses: ./.github/actions/ReRetweetAction
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          twi-cons-key: ${{ secrets.TWITTERCONSUMERKEY }}
          twi-cons-secret: ${{ secrets.TWITTERCONSUMERSECRET }}
          twi-token-key: ${{ secrets.TWITTERTOKENKEY }}
          twi-token-secret: ${{ secrets.TWITTERTOKENSECRET }}
